### ISSUE TITLE
The standard_modifier shouldn't be collection

### ISSUE THREAD

**Issue by andrew2net** [relaton/ieee-idams#7]
There aren't any docs with more than one `standard_modifier` in the ieee-rawbib dataset. And we use it as status in Relaton model, which is also single attribute.

**Comment by ronaldtse** [comment]
@andrew2net agreed, we just need a spec fixture that backs this up.

**Comment by andrew2net** [comment]
@ronaldtse We already have fixtures with `standard_modifier` attribute, but when there's only one element in doc then for the round-trip tests it doesn't matter if the attribute is collection or not. For XML the output is the same as input, but internally it is represented as Array. Do we ned to create tests for the attributes internal representations?

**Comment by ronaldtse** [comment]
You’re right. We don’t need an additional test for internal representation. Thanks.
